### ISSUE TITLE
Can you possible to horizontal scroll?

### ISSUE THREAD

**Issue by Govindbetterlives** [nggepe/simple_grid#10]
Hi, 
I placed so many grids. It's come one by one when I resize the screen resolution. So I need a horizontal scroll when I resize the screen.

Ref.
https://miro.medium.com/max/720/1*oWL3jUPkbfGtcpvS1u_Y-w.png

**Comment by nggepe** [comment]
Hi, I'm sorry, your image reference is out of the scope of this package. this package handle width of the grid that depend on the parent widget. when you set any `scroll widget` (infinity width) that the children is grid. it will never work.
