### ISSUE TITLE
Simple grid package issue while adding the another package.

### ISSUE THREAD

**Issue by Govindbetterlives** [nggepe/simple_grid#16]
Hi, 
We use simple grid package inside the drag_and_drop_lists 0.3.3 package. It shows an error like this "LayoutBuilder does not support returning intrinsic dimensions."

**Comment by nggepe** [comment]
Hi, thanks for your report. Actually this package is using LayoutBuilder to calculate the size of the box. Maybe I'll try to investigate it on `drag_and_drop_list` package.

Can you share your error and how to reproduce that?

**Comment by blprojects** [comment]
Yeah,
Here is the error.

The following assertion was thrown during performLayout():
 
LayoutBuilder does not support returning intrinsic dimensions.
 
Calculating the intrinsic dimensions would require running the layout callback speculatively, which
 
might mutate the live render object tree.

**Comment by Govindbetterlives** [comment]
Yeah, Here is the error,

The following assertion was thrown during performLayout():
 
LayoutBuilder does not support returning intrinsic dimensions.
 
Calculating the intrinsic dimensions would require running the layout callback speculatively, which
 
might mutate the live render object tree.

**Comment by nggepe** [comment]
Hi, can you share code too?

**Comment by nggepe** [comment]
Sorry, I think I have to close this issue. I can't reproduce your issue because I don't know how can you produce that.
