### ISSUE TITLE
Grid item shown as drop down while setting the "Spacing"

### ISSUE THREAD

**Issue by nizwar** [nggepe/simple_grid#3]
Can you fix this, when i set "spacing" to 10, all items show as a drop down, it doesn't shown horizontal like a grid view, 

i know it can be ignored and fixed by add margin on each item, but i think it must be great if it can be fixed on plugin side, as a feature that this great plugin already provides, thanks in advance!

**Comment by nggepe** [comment]
Thank you for giving an issue. I'll check it.

**Comment by nggepe** [comment]
hi @nizwar , may you can try again with the latest version of this package, I have launched a new update at version 0.0.6 
here is the release https://github.com/nggepe/simple_grid/releases/tag/0.0.6

**Comment by nizwar** [comment]
Its working now, thankyou for your great job!

**Comment by nggepe** [comment]
you're welcome, glad to help you 😀
