### ISSUE TITLE
Too many debug prints

### ISSUE THREAD

**Issue by thruthesky** [nggepe/simple_grid#4]
I had to comment out the `print` below, to stop debug print.

Thank you for your work.

![image](https://user-images.githubusercontent.com/5080329/111870041-a08ba100-89c5-11eb-846a-c74e6005da07.png)

**Comment by nggepe** [comment]
oh my god 😯 .. I'm sorry i'll fix it at a new version.

**Comment by nggepe** [comment]
thank you for reporting this.

**Comment by nggepe** [comment]
fix with https://github.com/nggepe/simple_grid/releases/tag/0.0.7
